name: testing workflow variables

on:
  workflow_dispatch

env:
  cloud: google-cloud

jobs:
  greeting_jobs:
    run-on:ubuntu-latest
    env:
     greeting: hello
    steps:
      -name: "say hellow mona its Monday"
       run: echo "$Greeting $First_Name is using $cloud"
       env: 
        First_Name: Neha
